#!/usr/bin/env bash
# Reverts what install.sh did. Leaves the system Spotify install untouched.
set -euo pipefail

PREFIX="${PREFIX:-$HOME/.local}"
SO_PATH="$PREFIX/lib/cef-noframe.so"
OUT_DESKTOP="$HOME/.local/share/applications/spotify.desktop"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

if [ -e "$SO_PATH" ]; then
  rm -f "$SO_PATH"
  say "Removed $SO_PATH"
fi

# Only remove the launcher if it's the one we generated (marker present).
if [ -e "$OUT_DESKTOP" ] && grep -q '^X-CefNoframe=1' "$OUT_DESKTOP"; then
  rm -f "$OUT_DESKTOP"
  say "Removed $OUT_DESKTOP"
  command -v update-desktop-database >/dev/null 2>&1 && \
    update-desktop-database "$HOME/.local/share/applications" >/dev/null 2>&1 || true
else
  say "Left $OUT_DESKTOP alone (not generated by this tool)"
fi

say "Uninstalled. Restart Spotify to go back to stock behaviour."
